collections:
 projects:
    led:
      order: 6
    microgamejam:
      order: 5
    sscl:
      order: 4
    gg:
      order: 3
    jackbox:
      order: 2
    ucla:
      order: 1
    heatsig:
      order: 0
    
      
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge