plugins:
  - jekyll-feed
domain: ambiguous.name
url: https://ambiguous.name

collections:
  projects:
  animations:
  readmefiles:
    output: true
      
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
excerpt_separator: <!--more-->